// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function CheckDeps(arg1) {
  return window['go']['main']['App']['CheckDeps'](arg1);
}

export function ClearLog() {
  return window['go']['main']['App']['ClearLog']();
}

export function Download(arg1) {
  return window['go']['main']['App']['Download'](arg1);
}

export function EnsureModel(arg1) {
  return window['go']['main']['App']['EnsureModel'](arg1);
}

export function FetchInfo(arg1) {
  return window['go']['main']['App']['FetchInfo'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function InstallEngines(arg1) {
  return window['go']['main']['App']['InstallEngines'](arg1);
}

export function InstallTool(arg1) {
  return window['go']['main']['App']['InstallTool'](arg1);
}

export function IsBusy() {
  return window['go']['main']['App']['IsBusy']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function MediaURL(arg1) {
  return window['go']['main']['App']['MediaURL'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PickAudioFile() {
  return window['go']['main']['App']['PickAudioFile']();
}

export function PickOutputDir() {
  return window['go']['main']['App']['PickOutputDir']();
}

export function RefreshRoformerModels() {
  return window['go']['main']['App']['RefreshRoformerModels']();
}

export function RevealPath(arg1) {
  return window['go']['main']['App']['RevealPath'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Separate(arg1, arg2) {
  return window['go']['main']['App']['Separate'](arg1, arg2);
}

export function SuggestedAccel() {
  return window['go']['main']['App']['SuggestedAccel']();
}

export function UpdateYtDlp() {
  return window['go']['main']['App']['UpdateYtDlp']();
}
