// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {deps} from '../models';
import {selfupdate} from '../models';
import {ytdl} from '../models';
import {settings} from '../models';
import {engine} from '../models';

export function ApplyUpdate():Promise<void>;

export function Bootstrap():Promise<main.Bootstrap>;

export function Cancel():Promise<void>;

export function CheckDeps(arg1:boolean):Promise<deps.Report>;

export function CheckUpdate():Promise<selfupdate.Status>;

export function ClearLog():Promise<void>;

export function Download(arg1:string):Promise<ytdl.Track>;

export function EnsureModel(arg1:string):Promise<void>;

export function FetchInfo(arg1:string):Promise<ytdl.Info>;

export function GetSettings():Promise<settings.Settings>;

export function InstallEngines(arg1:deps.EngineSpec):Promise<void>;

export function InstallTool(arg1:string):Promise<void>;

export function IsBusy():Promise<boolean>;

export function ListModels():Promise<Array<engine.Model>>;

export function MediaURL(arg1:string):Promise<string>;

export function OpenPath(arg1:string):Promise<void>;

export function PickAudioFile():Promise<string>;

export function PickOutputDir():Promise<string>;

export function RefreshRoformerModels():Promise<number>;

export function RevealPath(arg1:string):Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<settings.Settings>;

export function Separate(arg1:string,arg2:string):Promise<engine.Result>;

export function SuggestedAccel():Promise<string>;

export function UpdateYtDlp():Promise<void>;
